apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  annotations:
    # Specify the load balancer scheme as internet-facing to create a public-facing Network Load Balancer (NLB)
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
  labels:
    app: pgadmin
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: LoadBalancer
  selector:
    app: pgadmin