apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
     storage: 2Gi
  volumeMode: Filesystem
  storageClassName: ""
# El standard es para minikube
#  storageClassName: standard
#El Acces Mode es ReadWriteMany para algunos nodos puedan acceder al storage
  accessModes:
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: [efs_file_system_id]
#    - ReadWriteOnce
#  hostPath:
#    path: /var/lib/postgresql/data
#    type: DirectoryOrCreate
